/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_AddingVertexShouldSetVertexIdAndIncrementElemCount(void);
extern void test_AddingMoreThanSizeVerticesShouldReallocateAdjList(void);
extern void test_RemoveVertexShouldPutIndexInFreeListAndDecrementVertexCount(void);
extern void test_VertexInsertedAfterRemovalShouldHaveOldVertexId(void);
extern void test_InsertEdgeWithAdjLists(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestEset.c";
  UnityBegin();
  RUN_TEST(test_AddingVertexShouldSetVertexIdAndIncrementElemCount, 26);
  RUN_TEST(test_AddingMoreThanSizeVerticesShouldReallocateAdjList, 37);
  RUN_TEST(test_RemoveVertexShouldPutIndexInFreeListAndDecrementVertexCount, 69);
  RUN_TEST(test_VertexInsertedAfterRemovalShouldHaveOldVertexId, 101);
  RUN_TEST(test_InsertEdgeWithAdjLists, 137);

  return (UnityEnd());
}
