/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_Initialization(void);
extern void test_SetElementsInMatrixShouldGetThemInTheRightIndices(void);
extern void test_SetElementOutsideBoundaryShouldReturnWarning(void);
extern void test_AddingRowsReallocateMatrix(void);
extern void test_AddingColsReallocateMatrix(void);
extern void test_SetDefaultValuesShouldInitializeTheMatrixWithTheSameValue(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestMatrix.c";
  UnityBegin();
  RUN_TEST(test_Initialization, 49);
  RUN_TEST(test_SetElementsInMatrixShouldGetThemInTheRightIndices, 59);
  RUN_TEST(test_SetElementOutsideBoundaryShouldReturnWarning, 96);
  RUN_TEST(test_AddingRowsReallocateMatrix, 111);
  RUN_TEST(test_AddingColsReallocateMatrix, 125);
  RUN_TEST(test_SetDefaultValuesShouldInitializeTheMatrixWithTheSameValue, 137);

  return (UnityEnd());
}
