/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_ListOrderedInsertInsertsInOrder(void);
extern void test_ListWarnThatThereIsADuplicate(void);
extern void test_HeadInsertInsertsNodesInHead(void);
extern void test_SearchFindsNodeInListAndReturnsPointer(void);
extern void test_SearchDoesntFindNodeInEmptyList(void);
extern void test_SearchDoesntFindNodeNotPresentInList(void);
extern void test_SearchWithoutSavingInfo(void);
extern void test_DeleteNodeDeleteNodeInHead(void);
extern void test_DeleteNonExistentNodeWarnsNodeNotPresent(void);
extern void test_DeleteRestoreCorrectLinkBetweenNodes(void);
extern void test_HeadDeleteDeletesNodeInHead(void);
extern void test_jListMap(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestList.c";
  UnityBegin();
  RUN_TEST(test_ListOrderedInsertInsertsInOrder, 101);
  RUN_TEST(test_ListWarnThatThereIsADuplicate, 137);
  RUN_TEST(test_HeadInsertInsertsNodesInHead, 155);
  RUN_TEST(test_SearchFindsNodeInListAndReturnsPointer, 194);
  RUN_TEST(test_SearchDoesntFindNodeInEmptyList, 226);
  RUN_TEST(test_SearchDoesntFindNodeNotPresentInList, 236);
  RUN_TEST(test_SearchWithoutSavingInfo, 259);
  RUN_TEST(test_DeleteNodeDeleteNodeInHead, 283);
  RUN_TEST(test_DeleteNonExistentNodeWarnsNodeNotPresent, 295);
  RUN_TEST(test_DeleteRestoreCorrectLinkBetweenNodes, 307);
  RUN_TEST(test_HeadDeleteDeletesNodeInHead, 331);
  RUN_TEST(test_jListMap, 370);

  return (UnityEnd());
}
