/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_InitArrayWithGoodInitAndDeleteFunctions(void);
extern void test_InitArrayWithoutInitAndDeleteFunctionsShouldReturnError(void);
extern void test_GetArrayElementInPosition0AfterInitializationShouldReturnNull(void);
extern void test_GetArrayElementOutOfBoundShouldReturnWarning(void);
extern void test_SetElemInPosition0ShouldSaveElementInArrayAndIncrementElemCount(void);
extern void test_SetElemOutOfBoundShouldReturnWarningAndLeaveElemCountZero(void);
extern void test_SetElemWithNegativeIndexShouldReturnWarningAndLeaveElemCountZero(void);
extern void test_SetElemInPositionAlreadyOccupiedFreeOldElem(void);
extern void test_DeleteItemInPositionSetThatItemToNull(void);
extern void test_DeleteItemOutOfArrayBoundShouldReturnWarning(void);
extern void test_ResizeArrayToSmallerSizeShouldDeallocateUnusedElements(void);
extern void test_ResizeArrayToBiggerSizeShouldAllocateNewNullPointersAndIncrementArraySize(void);
extern void test_ResizeWithNegativeNewSizeShouldReturnError(void);
extern void test_MapElementsWithPrintFunctionPrintElements(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestArray.c";
  UnityBegin();
  RUN_TEST(test_InitArrayWithGoodInitAndDeleteFunctions, 59);
  RUN_TEST(test_InitArrayWithoutInitAndDeleteFunctionsShouldReturnError, 66);
  RUN_TEST(test_GetArrayElementInPosition0AfterInitializationShouldReturnNull, 72);
  RUN_TEST(test_GetArrayElementOutOfBoundShouldReturnWarning, 79);
  RUN_TEST(test_SetElemInPosition0ShouldSaveElementInArrayAndIncrementElemCount, 87);
  RUN_TEST(test_SetElemOutOfBoundShouldReturnWarningAndLeaveElemCountZero, 104);
  RUN_TEST(test_SetElemWithNegativeIndexShouldReturnWarningAndLeaveElemCountZero, 113);
  RUN_TEST(test_SetElemInPositionAlreadyOccupiedFreeOldElem, 122);
  RUN_TEST(test_DeleteItemInPositionSetThatItemToNull, 138);
  RUN_TEST(test_DeleteItemOutOfArrayBoundShouldReturnWarning, 151);
  RUN_TEST(test_ResizeArrayToSmallerSizeShouldDeallocateUnusedElements, 157);
  RUN_TEST(test_ResizeArrayToBiggerSizeShouldAllocateNewNullPointersAndIncrementArraySize, 173);
  RUN_TEST(test_ResizeWithNegativeNewSizeShouldReturnError, 203);
  RUN_TEST(test_MapElementsWithPrintFunctionPrintElements, 209);

  return (UnityEnd());
}
