/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_CheckInitialization(void);
extern void test_AddElementToSet(void);
extern void test_DeleteElement(void);
extern void test_SearchElementWithoutSavingInfo(void);
extern void test_SearchElementSavingInfo(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestSet.c";
  UnityBegin();
  RUN_TEST(test_CheckInitialization, 94);
  RUN_TEST(test_AddElementToSet, 101);
  RUN_TEST(test_DeleteElement, 124);
  RUN_TEST(test_SearchElementWithoutSavingInfo, 150);
  RUN_TEST(test_SearchElementSavingInfo, 173);

  return (UnityEnd());
}
