/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_CheckInitialization(void);
extern void test_AddingVertexWithDataToGraph(void);
extern void test_AddVertexWithoutDataToGraph(void);
extern void test_SearchVertexWithoutSavingDataAssociated(void);
extern void test_SearchVertexSavingItsData(void);
extern void test_addEdgeToVertexAdjList(void);
extern void test_removeVertex(void);
extern void test_removeEdge(void);
extern void test_TransposeGraph(void);
extern void test_PrintGraph(void);
extern void test_Dfs(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "TestGraph.c";
  UnityBegin();
  RUN_TEST(test_CheckInitialization, 82);
  RUN_TEST(test_AddingVertexWithDataToGraph, 87);
  RUN_TEST(test_AddVertexWithoutDataToGraph, 97);
  RUN_TEST(test_SearchVertexWithoutSavingDataAssociated, 104);
  RUN_TEST(test_SearchVertexSavingItsData, 111);
  RUN_TEST(test_addEdgeToVertexAdjList, 132);
  RUN_TEST(test_removeVertex, 168);
  RUN_TEST(test_removeEdge, 203);
  RUN_TEST(test_TransposeGraph, 222);
  RUN_TEST(test_PrintGraph, 260);
  RUN_TEST(test_Dfs, 289);

  return (UnityEnd());
}
